/**
 * Shared contract between the browser client and the `PlanningRoom`
 * Durable Object (PartyServer). Everything that crosses the WebSocket or
 * the room-creation HTTP endpoint is typed here.
 */

/* --- Core state --- */

export type VoteSystem = 'fibonacci' | 'numbers' | 'tshirt';

export const VOTE_SYSTEMS: VoteSystem[] = ['fibonacci', 'numbers', 'tshirt'];

/**
 * A player inside a room. This replaces the previous Convex `sessions` +
 * `participants` rows, flattened into a single record owned by the room.
 */
export interface Participant {
  /** Stable player identity: a UUID generated by the browser (localStorage). */
  sessionId: string;
  /** Display name chosen in the welcome popup. */
  name: string;
  /** Selected card value. `''` means the player has not voted. */
  vote: string;
  isAdmin: boolean;
  isAllowedVote: boolean;
  /** Last activity timestamp, used by the 30-day room cleanup alarm. */
  lastSeenAt: number;
}

/** Replaces the previous Convex `rooms` row. */
export interface Room {
  roomSlug: string;
  prettyName: string;
  isLocked: boolean;
  isRevealed: boolean;
  usersCanReveal: boolean;
  voteSystem: VoteSystem;
  currentStoryUrl: string;
  updatedAt: number;
}

/** The full room snapshot the server broadcasts to every connection. */
export interface RoomState {
  room: Room;
  participants: Participant[];
}

/* --- Messages: client -> server --- */

export type ClientMessage =
  /** Join (or re-join) the room as the given player. */
  | { type: 'join'; sessionId: string; name: string }
  /** Cast or clear a vote (`''` clears). */
  | { type: 'vote'; vote: string }
  /** Show or hide the table. Allowed for admins, or anyone if usersCanReveal. */
  | { type: 'reveal'; isRevealed: boolean }
  /** Clear every vote and hide the table (same permission as reveal). */
  | { type: 'reset-votes' }
  /** Change the voting system. Admin only; clears all votes and hides. */
  | { type: 'set-vote-system'; voteSystem: VoteSystem }
  /** Lock/unlock voting. Admin only. */
  | { type: 'set-locked'; isLocked: boolean }
  /** Toggle whether non-admin players can reveal. Admin only. */
  | { type: 'set-users-can-reveal'; usersCanReveal: boolean }
  /** Set the current story URL. Admin only. */
  | { type: 'set-story-url'; currentStoryUrl: string }
  /** Hand admin status over to another player (single-admin rule). Admin only. */
  | { type: 'promote-admin'; targetSessionId: string }
  /** Remove a player from the room. Admin only, cannot target yourself. */
  | { type: 'kick'; targetSessionId: string }
  /** Toggle another player's ability to vote. Admin only. */
  | {
      type: 'set-allowed-vote';
      targetSessionId: string;
      isAllowedVote: boolean;
    }
  /** Explicitly leave the room. */
  | { type: 'leave' }
  /** Delete the room and disconnect everyone. Admin only. */
  | { type: 'delete-room' };

/* --- Messages: server -> client --- */

export type ServerMessage =
  /** Full room snapshot, sent on connect and after every change. */
  | { type: 'state'; state: RoomState }
  /** The room does not exist (yet). Client redirects home. */
  | { type: 'room-not-found' }
  /** This connection's player was removed by an admin. */
  | { type: 'kicked' }
  /** An operation was rejected. `message` is human-readable. */
  | { type: 'error'; message: string };

/* --- Room creation (HTTP POST /api/rooms) --- */

export interface CreateRoomPayload {
  roomName: string;
  voteSystem: VoteSystem;
  playerReveal: boolean;
  playerChangeVote: boolean;
  playerAddTicket: boolean;
  creatorSessionId: string;
  creatorName: string;
}

export interface CreateRoomResult {
  roomSlug: string;
}

/** Type guard used on both sides of the wire. */
export function isVoteSystem(value: unknown): value is VoteSystem {
  return (
    typeof value === 'string' && (VOTE_SYSTEMS as string[]).includes(value)
  );
}
